apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mkdocs-helm-chart.fullname" . }}
  labels:
    {{- include "mkdocs-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mkdocs-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mkdocs-helm-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: docs
              mountPath: /docs
          command: ["mkdocs", "serve", "-a", "0.0.0.0:8000", "-f", "/docs/mkdocs.yml"]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: docs
          hostPath:
            path: {{ .Values.docs.path }}
            type: Directory